### ISSUE TITLE
Support externel $refs in openapi schema

### ISSUE THREAD

**Issue by Kisfejes** [Q42/openapi-typescript-validator#11]
In larger projects the openapi schema file is usually divided to more parts, but currently it's not handled in this package, which casues an ajv compilation error if there is any external $ref.

main.yml
```yml
components:
  schemas:
    UserList:
      type: array
      items:
        $ref: './user.yaml#/definitions/User'
```

user.yml
```yml
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    required: ['id']
```

Currently the external refs are not handled in `@openapi-contrib/openapi-schema-to-json-schema` https://github.com/openapi-contrib/openapi-schema-to-json-schema#features
>NOTE: $refs are not handled in any way, so please use a resolver such as [json-ref-resolver](https://github.com/stoplightio/json-ref-resolver) prior to using this package.

I've created a pull request which uses `@apidevtools/json-schema-ref-parser` to process external $refs.
